#!/usr/bin/env python3
"""
Generate src/config_defaults.h from meson option values.

Invoked by meson at configure-time via custom_target. Emits a header
file with two NULL-terminated arrays of C string literals — the
compile-time defaults for binaries.list and files.merkle paths.

Usage:
    gen-config-defaults.py OUTPUT_PATH \\
        --binaries-paths PATH1 PATH2 ... \\
        --files-paths PATH1 PATH2 ...

Strings are emitted with C-escape rules (printable ASCII only — non-ASCII
or control characters in a meson option value cause a hard error rather
than corrupt the generated header).
"""

import argparse
import re
import sys
from pathlib import Path


_VALID_PATH_CHARS = re.compile(r'^[\x20-\x7e]*$')


def c_escape(s: str) -> str:
    """C string escape (for the literal inside double quotes)."""
    if not _VALID_PATH_CHARS.match(s):
        raise SystemExit(
            f'gen-config-defaults: path contains non-printable-ASCII '
            f'or non-ASCII bytes: {s!r}'
        )
    out = []
    for ch in s:
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        else:
            out.append(ch)
    return ''.join(out)


def emit_array(name: str, paths: list) -> str:
    if not paths:
        # Single sentinel — keeps the C reader's NULL-termination contract
        # uniform whether the array is empty or populated.
        return (
            f'static const char *const {name}[] = {{\n'
            f'    NULL,\n'
            f'}};\n'
        )
    lines = [f'static const char *const {name}[] = {{']
    for p in paths:
        lines.append(f'    "{c_escape(p)}",')
    lines.append('    NULL,')
    lines.append('};')
    return '\n'.join(lines) + '\n'


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('output', type=Path, help='destination header file')
    ap.add_argument(
        '--binaries-paths',
        nargs='*',
        default=[],
        help='Compile-time default paths for binaries.list',
    )
    ap.add_argument(
        '--files-paths',
        nargs='*',
        default=[],
        help='Compile-time default paths for files.merkle',
    )
    args = ap.parse_args()

    body = (
        '/*\n'
        ' * Auto-generated by scripts/gen-config-defaults.py — do not edit.\n'
        ' * Regenerated whenever meson option binaries_paths or files_paths\n'
        ' * changes. Holds the compile-time default allowlists.\n'
        ' *\n'
        ' * Both arrays are NULL-terminated. An empty array is the\n'
        ' * v0.4.x-compatible default (no userspace attestation; manifest\n'
        ' * grows three new STABLE fields with empty values).\n'
        ' */\n'
        '#pragma once\n\n'
        + emit_array('CONFIG_DEFAULT_BINARIES_PATHS', args.binaries_paths)
        + '\n'
        + emit_array('CONFIG_DEFAULT_FILES_PATHS', args.files_paths)
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(body)
    return 0


if __name__ == '__main__':
    sys.exit(main())
